[package]
org = "wso2"
name = "terminology_service"
version = "1.0.0"
distribution = "2201.8.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="health.fhir.r4.terminology"
version="4.1.1"

